# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglik_cpp <- function(theta, W, X, Y, weights, nReg, nThreads) {
    .Call(`_OPSR_loglik_cpp`, theta, W, X, Y, weights, nReg, nThreads)
}

opsr_prepare_coefs <- function(theta, nReg) {
    .Call(`_OPSR_opsr_prepare_coefs`, theta, nReg)
}

opsr_check_omp <- function() {
    .Call(`_OPSR_opsr_check_omp`)
}

opsr_max_threads <- function() {
    .Call(`_OPSR_opsr_max_threads`)
}

